Fourth homework
Yulia-Yakovleva/BI_2019_Python pull request #5
Opened 2019-10-27 23:38 UTC by Yulia-Yakovleva

2019-10-30 19:34 UTC, AleksandrSl commented
Старые файлы не надо удалять, почему тебе это показалось логичным?

2019-10-30 19:42 UTC, AleksandrSl requested changes

2019-10-30 19:42 UTC, AleksandrSl commented on common_words.py
> +    out_list.sort()
Лучше все же `sorted` использовать по возможности, изменять in place что-то не очень хорошо, можно было написать `','.join(sorted(out_list))`

2019-10-30 19:42 UTC, AleksandrSl commented on common_words.py
> +    return out_string
Какая сложность решения?

2019-10-30 19:42 UTC, AleksandrSl commented on group_equal.py
> +    if len(input_list) < 1:
Лучше явно на ноль проверить, длина меньше 0 быть не может, немного странно выглядит)

2019-10-30 19:42 UTC, AleksandrSl commented on group_equal.py
> +    if len(input_list) < 1:
Или вообще написать `if input_list` для пустого списка это будет `false`

2019-10-30 19:42 UTC, AleksandrSl commented on group_equal.py
> +    elif len(input_list) == 1:
Это условие на самом деле можно объединить с тем что в `else` происходит

2019-10-30 19:42 UTC, AleksandrSl commented on group_equal.py
> +        for element in input_list:
А у тебя разве первый елемент тут два раза не добавится?

2019-10-30 19:42 UTC, AleksandrSl commented on create_intervals.py
> +    input_list = sorted(list(input_set))
Падает на пустом множестве

2019-10-31 17:45 UTC, Yulia-Yakovleva commented on group_equal.py
> +        for element in input_list:
добавляется, но только тогда, когда я пытаюсь делать input с консоли. если просто вызывать функцию от списка, то все норм, я на это тоже обратила внимание

2020-02-15 08:23 UTC, closed without merging